import { env } from "../config/env.js";

export interface GeneratedArcaneRiddle {
  question: string;
  answer: string;
  hint?: string;
  reward: number;
  notes: string;
}

const SYSTEM_PROMPT = "You are the Arcane Scribe for The Wizards of Ark, an ARK: Survival Ascended community.

Create original, difficult, AI-resistant community riddles for human players.

Rules:
- The subject must be meaningfully related to ARK: Survival Ascended and/or The Wizards of Ark.
- Use WoA wizard/arcane flavor when it fits.
- Do not require obscure real-world trivia outside ARK/WoA.
- Do not make the answer obvious by naming, describing, or listing its defining traits directly.
- Avoid common internet riddle templates, famous riddles, memes, quotes, lyrics, or searchable stock phrasing.
- Avoid simple acrostics, first-letter tricks, explicit coordinates, map names as giveaway clues, or obvious wordplay that can be mechanically searched.
- Use layered clues, misdirection, ARK-specific context, and an internal thematic connection that rewards players who know the game/community.
- The answer must be a single concrete ARK/WoA concept, creature, item, mechanic, location type, resource, structure, or WoA concept that players could reasonably know.
- Keep the riddle concise enough for Discord: usually 4–8 lines.
- Make it solvable through inference, but deliberately resistant to generic AI pattern matching.
- Never mention that it was generated by AI.
- Return ONLY valid JSON with keys: question, answer, hint, reward, notes.
- reward must be an integer from 5 to 50.
- notes should briefly explain the intended solving path and why the clues are not giveaways. Do not expose chain-of-thought or hidden reasoning.";

export async function generateArcaneRiddle(): Promise<GeneratedArcaneRiddle> {
  if (!env.openAiApiKey) throw new Error("OPENAI_API_KEY is not configured.");
  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: "Bearer " + env.openAiApiKey },
    body: JSON.stringify({
      model: env.openAiModel,
      input: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: "Forge one fresh WoA riddle now. Do not reuse a familiar riddle structure. Favor an unexpected ARK connection and a fair but difficult inference path." }
      ],
      max_output_tokens: 700
    })
  });
  if (!response.ok) {
    let detail = "";
    try {
      const errorData = await response.json() as any;
      detail = errorData?.error?.message || errorData?.message || "";
    } catch {
      detail = await response.text().catch(() => "");
    }
    throw new Error("OpenAI request failed (" + response.status + ")" + (detail ? ": " + detail : "."));
  }
  const data = await response.json() as any;
  const outputText = typeof data.output_text === "string"
    ? data.output_text
    : (data.output ?? []).flatMap((item: any) => item.content ?? []).map((item: any) => item.text ?? "").join("");
  if (!outputText) throw new Error("OpenAI returned no riddle.");
  const raw = outputText.trim().replace(/^\`\`\`json\s*/i, "").replace(/\s*\`\`\`$/i, "");
  let parsed: any;
  try { parsed = JSON.parse(raw); } catch { throw new Error("OpenAI returned invalid riddle JSON."); }
  if (typeof parsed.question !== "string" || typeof parsed.answer !== "string" || !parsed.question.trim() || !parsed.answer.trim()) {
    throw new Error("Generated riddle was missing a question or answer.");
  }
  const reward = Number.isInteger(parsed.reward) ? Math.min(50, Math.max(5, parsed.reward)) : 15;
  return {
    question: parsed.question.trim(),
    answer: parsed.answer.trim(),
    hint: typeof parsed.hint === "string" ? parsed.hint.trim() || undefined : undefined,
    reward,
    notes: typeof parsed.notes === "string" ? parsed.notes.trim().slice(0, 900) : "Original layered WoA/ARK riddle."
  };
}
