import { randomUUID } from "node:crypto";
import { prisma } from "../database/prisma.js";
import { arcaneStore,type ArcaneCharacterRecord } from "./store.js";
import { getClass,getItem,getPveEnemy } from "./catalog.js";
import { sigilStore } from "../sigilStore.js";
export type BattleState={hp:number;mana:number;shield:number;weakened:number;defended:boolean;relicUsed:boolean;evasion:number;specialCooldown:number;log:string[]};
export type BattleRecord={id:string;guildId:string;challengerId:string;opponentId:string;turnUserId:string;status:string;round:number;state:any;messageId?:string|null};
const stats=(c:ArcaneCharacterRecord)=>{const cls=getClass(c.classId)!;const ar=getItem(c.armorId),fo=getItem(c.focusId);return {maxHp:cls.base.maxHp+(ar?.stats?.maxHp||0),maxMana:cls.base.maxMana+(ar?.stats?.maxMana||0),power:cls.base.power+(ar?.stats?.power||0),defense:cls.base.defense+(ar?.stats?.defense||0),speed:cls.base.speed+(ar?.stats?.speed||0)};};
const state=(c:ArcaneCharacterRecord):BattleState=>({hp:stats(c).maxHp,mana:stats(c).maxMana,shield:0,weakened:0,defended:false,relicUsed:false,evasion:0,specialCooldown:0,log:[]});
class BattleStore {
async get(id:string){return prisma.arcaneBattle.findUnique({where:{id}}) as any;}
async active(guildId:string,userId:string){return prisma.arcaneBattle.findFirst({where:{guildId,status:"active",OR:[{challengerId:userId},{opponentId:userId}]},orderBy:{createdAt:"desc"}}) as any;}
async create(guildId:string,a:string,b:string){const ca=await arcaneStore.get(guildId,a),cb=await arcaneStore.get(guildId,b);if(!ca||!cb)throw new Error("Both wizards need characters.");const first=(stats(ca).speed+(getItem(ca.relicIds.find(id=>getItem(id)?.effect?.type==="initiative")||"")?.effect?.value||0))>=(stats(cb).speed+(getItem(cb.relicIds.find(id=>getItem(id)?.effect?.type==="initiative")||"")?.effect?.value||0))?a:b;return this.get((await prisma.arcaneBattle.create({data:{id:randomUUID(),guildId,challengerId:a,opponentId:b,turnUserId:first,status:"pending",round:1,state:{[a]:state(ca),[b]:state(cb)}}})).id);}
async createPve(guildId:string,userId:string,enemyId:string){const c=await arcaneStore.get(guildId,userId),enemy=getPveEnemy(enemyId);if(!c||!enemy)throw new Error("Wizard or enemy not found.");if(await this.active(guildId,userId))throw new Error("You already have an active Trial.");const id=randomUUID();const first=userId;return this.get((await prisma.arcaneBattle.create({data:{id,guildId,challengerId:userId,opponentId:"npc:"+enemy.id,turnUserId:first,status:"active",round:1,state:{[userId]:state(c),["npc:"+enemy.id]:{hp:enemy.maxHp,mana:enemy.maxMana,shield:0,weakened:0,defended:false,relicUsed:false,evasion:0,specialCooldown:0,log:[]}}}})).id);}
async setMessage(id:string,messageId:string){await prisma.arcaneBattle.update({where:{id},data:{messageId}});}
async act(id:string,userId:string,action:string,itemId?:string){
const b:any=await this.get(id);if(!b||b.status!=="active")throw new Error("That trial is closed.");if(b.turnUserId!==userId)throw new Error("It is not your turn.");
const targetId=b.challengerId===userId?b.opponentId:b.challengerId;const actor=await arcaneStore.get(b.guildId,userId);const pve=b.opponentId.startsWith("npc:");const enemy=pve?getPveEnemy(b.opponentId.slice(4)):undefined;const target=enemy?undefined:await arcaneStore.get(b.guildId,targetId);if(!actor||(pve&&!enemy)||(!pve&&!target))throw new Error("Battle data is missing.");
const s:any=b.state,me:BattleState=s[userId],foe:BattleState=s[targetId],as=stats(actor),ts=pve?enemy!:{maxHp:stats(target!).maxHp,maxMana:stats(target!).maxMana,power:stats(target!).power,defense:stats(target!).defense,speed:stats(target!).speed};let text="";me.defended=false;
const hit=(raw:number)=>{if(foe.evasion>0&&Math.random()<foe.evasion/100)return {dmg:0,blocked:0,evasion:true};let dmg=Math.max(1,raw+as.power-ts.defense-(foe.defended?6:0)-foe.weakened);const blocked=Math.min(foe.shield,dmg);foe.shield-=blocked;dmg-=blocked;foe.hp=Math.max(0,foe.hp-dmg);return {dmg,blocked,evasion:false};};
if(action==="attack"){const h=hit(Math.floor(Math.random()*7)+7);text="⚔️ "+actor.name+" struck for **"+h.dmg+"** damage."+(h.blocked?" "+h.blocked+" was warded.":"");}
else if(action==="defend"){me.defended=true;me.shield=Math.min(35,me.shield+12);text="🛡️ "+actor.name+" raised a ward.";}
else if(action==="focus"){me.mana=Math.min(as.maxMana,me.mana+18);text="🔮 "+actor.name+" recovered **18 Mana**.";}
else if(action==="spell"){const item=getItem(itemId||"");if(!item||item.kind!=="spell"||!actor.equippedSpellIds.includes(item.id))throw new Error("That spell is not equipped.");const manaCost=item.manaCost??8;if(me.mana<manaCost)throw new Error("Not enough Mana. You need **"+manaCost+" Mana** to cast **"+item.name+"**.");me.mana-=manaCost;const v=item.effect?.value||10;switch(item.effect?.type){case"heal":me.hp=Math.min(as.maxHp,me.hp+v);text="✨ "+actor.name+" restored **"+v+" HP**.";break;case"shield":case"guard":me.shield=Math.min(35,me.shield+v);text="🛡️ "+actor.name+" raised a **"+v+"** ward.";break;case"mana":me.mana=Math.min(as.maxMana,me.mana+v);text="🔮 "+actor.name+" restored **"+v+" Mana**.";break;case"weaken":foe.weakened=Math.min(8,Math.ceil(v/2));text="🌑 "+actor.name+" weakened the enemy.";break;case"drain":{const h=hit(v);me.hp=Math.min(as.maxHp,me.hp+Math.floor(h.dmg/2));text=h.evasion?"🌑 "+actor.name+" cast **"+item.name+"**, but the enemy evaded it.":"🌑 "+actor.name+" drained **"+h.dmg+" HP**.";break;}default:{const h=hit(v);text=h.evasion?item.emoji+" "+actor.name+" cast **"+item.name+"**, but the enemy evaded the spell.":item.emoji+" "+actor.name+" cast **"+item.name+"** for **"+h.dmg+"** damage.";}}actor.equippedSpellIds=actor.equippedSpellIds.filter(id=>id!==item.id);actor.ownedItemIds=actor.ownedItemIds.filter(id=>id!==item.id);await arcaneStore.save(actor);}
else if(action==="relic"){const item=getItem(itemId||"");if(!item||item.kind!=="relic"||!actor.relicIds.includes(item.id))throw new Error("That relic is not equipped.");if(me.relicUsed)throw new Error("Your relic has already been used.");me.relicUsed=true;actor.relicIds=actor.relicIds.filter(id=>id!==item.id);actor.ownedItemIds=actor.ownedItemIds.filter(id=>id!==item.id);await arcaneStore.save(actor);if(item.effect?.type==="shield"){me.shield=Math.min(35,me.shield+item.effect.value);text="🔶 "+actor.name+" invoked **"+item.name+"** and gained **"+item.effect.value+" Ward**.";}else if(item.effect?.type==="evasion"){me.evasion=Math.max(me.evasion,item.effect.value);text="🔶 "+actor.name+" invoked **"+item.name+"** and gained **"+item.effect.value+"% evasion** for the battle.";}else if(item.effect?.type==="initiative"){text="🔶 "+actor.name+" invoked **"+item.name+"** and seized the initiative — act again immediately.";}else{text="🔶 "+actor.name+" invoked **"+item.name+"**.";} }
else if(action==="special"){if(me.specialCooldown>0)throw new Error("Your special move is on cooldown for **"+me.specialCooldown+"** more turn(s).");const special=getClass(actor.classId)?.special;if(!special)throw new Error("Your Wizard has no special move.");if(me.mana<special.manaCost)throw new Error("Not enough Mana. You need **"+special.manaCost+" Mana** for **"+special.name+"**.");me.mana-=special.manaCost;switch(actor.classId){case"ember_mage":{const r=hit(24);text="🔥 "+actor.name+" unleashed **"+special.name+"** for **"+r.dmg+"** damage.";break;}case"frostweaver":{const r=hit(17);foe.weakened=Math.max(foe.weakened,3);text="❄️ "+actor.name+" cast **"+special.name+"** for **"+r.dmg+"** damage and weakened the enemy.";break;}case"verdant_warden":{const before=me.hp;me.hp=Math.min(as.maxHp,me.hp+30);me.shield=Math.min(35,me.shield+10);text="🌿 "+actor.name+" invoked **"+special.name+"**, restoring **"+(me.hp-before)+" HP** and gaining **10 Ward**.";break;}case"storm_herald":{const first=hit(10),second=hit(8);text="⚡ "+actor.name+" unleashed **"+special.name+"** for **"+(first.dmg+second.dmg)+"** total damage.";break;}case"voidcaller":{const r=hit(18);foe.weakened=Math.max(foe.weakened,2);foe.mana=Math.max(0,foe.mana-12);text="🌑 "+actor.name+" invoked **"+special.name+"** for **"+r.dmg+"** damage, draining **12 Mana** and weakening the enemy.";break;}case"sigilbinder":{const r=hit(20);me.shield=Math.min(35,me.shield+10);text="🔮 "+actor.name+" invoked **"+special.name+"** for **"+r.dmg+"** damage and gained **10 Ward**.";break;}default:throw new Error("Unknown Wizard class.");}me.specialCooldown=3;}
else throw new Error("Unknown battle action.");
me.weakened=Math.max(0,me.weakened-1);foe.weakened=Math.max(0,foe.weakened-1);if(action!=="special"&&me.specialCooldown>0)me.specialCooldown=Math.max(0,me.specialCooldown-1);me.log=[...(me.log||[]),text].slice(-6);s.__battleLog=[...(s.__battleLog||[]),text].slice(-5);
s.__lastMoveUserId=userId;if(foe.hp<=0){s.__winnerId=userId;b.status="finished";await prisma.arcaneBattle.update({where:{id},data:{status:"finished",state:s}});if(pve){await arcaneStore.addXp(actor,enemy!.rewardXp);await sigilStore.addTransaction(b.guildId,userId,enemy!.rewardSigils,"Arcane PvE victory: "+enemy!.name,{type:"award"});return {battle:b,message:text,winnerId:userId,pve:true,rewardXp:enemy!.rewardXp,rewardSigils:enemy!.rewardSigils};}await arcaneStore.addXp(actor,50);await arcaneStore.addXp(target!,15);return {battle:b,message:text,winnerId:userId};}
if(pve){const rarity=enemy!.rarity.toLowerCase();const missChance=rarity==="common"?0.18:rarity==="uncommon"?0.14:rarity==="rare"?0.1:rarity==="epic"?0.07:0.04;const sillyChance=rarity==="common"?0.1:rarity==="uncommon"?0.09:rarity==="rare"?0.08:rarity==="epic"?0.07:0.06;const roll=Math.random();if(roll<missChance){text+=" "+enemy!.emoji+" "+enemy!.name+" lunged forward... and completely missed. 😂";me.log=[...(me.log||[]),enemy!.emoji+" "+enemy!.name+" completely missed. 😂"].slice(-6);s.__battleLog=[...(s.__battleLog||[]),enemy!.emoji+" "+enemy!.name+" completely missed. 😂"].slice(-5);}else if(roll<missChance+sillyChance){const antics=[enemy!.name+" tripped over its own spellbook. 📖😂",enemy!.name+" sneezed and accidentally scattered sparks everywhere. ✨😂",enemy!.name+" paused to dramatically adjust its imaginary wizard hat. 🎩😂",enemy!.name+" tried a fancy spell... and forgot the incantation. 🪄😂"];const gag=antics[Math.floor(Math.random()*antics.length)];const ward=rarity==="legendary"?8:rarity==="epic"?6:rarity==="rare"?4:2;me.shield=Math.min(35,me.shield+ward);text+=" "+gag+(ward?" It recovered behind a **"+ward+"** ward.":"");me.log=[...(me.log||[]),gag+(ward?" Ward +"+ward+".":"")].slice(-6);s.__battleLog=[...(s.__battleLog||[]),gag+(ward?" Ward +"+ward+".":"")].slice(-5);}else{const critChance=rarity==="common"?0.05:rarity==="uncommon"?0.07:rarity==="rare"?0.1:rarity==="epic"?0.13:0.16;const crit=Math.random()<critChance;const ai=Math.max(1,Math.floor(Math.random()*7)+5+enemy!.power-as.defense-(me.defended?6:0)-me.weakened+(crit?5:0));const blocked=Math.min(me.shield,ai);me.shield-=blocked;me.hp=Math.max(0,me.hp-(ai-blocked));const hitText=enemy!.emoji+" "+enemy!.name+(crit?" landed a **critical** strike":" struck")+" for **"+(ai-blocked)+"** damage."+(blocked?" "+blocked+" was warded.":"");text+=" "+hitText;me.log=[...(me.log||[]),hitText].slice(-6);s.__battleLog=[...(s.__battleLog||[]),hitText].slice(-5);}if(me.hp<=0){s.__winnerId=b.opponentId;b.status="finished";await prisma.arcaneBattle.update({where:{id},data:{status:"finished",state:s}});await arcaneStore.addXp(actor,Math.max(10,Math.floor(enemy!.rewardXp/3)));return {battle:b,message:text,winnerId:enemy!.id,pve:true};}b.round++;await prisma.arcaneBattle.update({where:{id},data:{round:b.round,state:s,turnUserId:userId}});return {battle:b,message:text,winnerId:null,pve:true};}const bonusTurn=action==="relic"&&itemId?getItem(itemId)?.effect?.type==="initiative":false;b.turnUserId=bonusTurn?userId:targetId;b.round++;await prisma.arcaneBattle.update({where:{id},data:{turnUserId:b.turnUserId,round:b.round,state:s}});return {battle:b,message:text,winnerId:null};
}
}
export const battleStore=new BattleStore();