export type ArcaneClassId = "ember_mage"|"frostweaver"|"verdant_warden"|"storm_herald"|"voidcaller"|"sigilbinder";
export type ArcaneItemKind = "spell"|"armor"|"focus"|"relic"|"cosmetic"|"consumable";
export interface ArcaneStats { maxHp:number; maxMana:number; power:number; defense:number; speed:number; }
export interface ArcaneClass { id:ArcaneClassId; name:string; emoji:string; role:string; description:string; base:ArcaneStats; starterSpells:string[]; special:{name:string;description:string;manaCost:number}; }
export interface ArcaneItem { id:string; name:string; emoji:string; kind:ArcaneItemKind; rarity:string; cost:number; description:string; classId?:ArcaneClassId; minLevel?:number; stats?:Partial<ArcaneStats>; effect?:{type:string;value:number}; manaCost?:number; }
export interface ArcanePveEnemy { id:string; name:string; emoji:string; rarity:string; description:string; maxHp:number; maxMana:number; power:number; defense:number; speed:number; rewardXp:number; rewardSigils:number; }
export const ARCANE_CLASSES:ArcaneClass[]=[
{id:"ember_mage",name:"Ember Mage",emoji:"🔥",role:"Damage",description:"Aggressive fire magic.",base:{maxHp:95,maxMana:70,power:15,defense:8,speed:10},starterSpells:["ember_bolt","ember_ward"],special:{name:"Inferno",description:"Unleash a devastating burst of flame against the enemy.",manaCost:30}},
{id:"frostweaver",name:"Frostweaver",emoji:"❄️",role:"Control",description:"Cold magic and battlefield control.",base:{maxHp:105,maxMana:70,power:10,defense:11,speed:8},starterSpells:["frost_shard","frost_veil"],special:{name:"Absolute Zero",description:"Strike with freezing magic and leave the enemy weakened.",manaCost:30}},
{id:"verdant_warden",name:"Verdant Warden",emoji:"🌿",role:"Support",description:"Healing and protection.",base:{maxHp:120,maxMana:65,power:8,defense:14,speed:7},starterSpells:["verdant_bloom","thorn_guard"],special:{name:"Nature's Rebirth",description:"Restore health and raise a protective living ward.",manaCost:30}},
{id:"storm_herald",name:"Storm Herald",emoji:"⚡",role:"Speed",description:"Fast lightning and burst attacks.",base:{maxHp:90,maxMana:75,power:12,defense:8,speed:16},starterSpells:["storm_bolt","thunderstep"],special:{name:"Tempest Rush",description:"A rapid lightning assault that hits with exceptional force.",manaCost:30}},
{id:"voidcaller",name:"Voidcaller",emoji:"🌑",role:"Debuff",description:"Weakens enemies and drains power.",base:{maxHp:100,maxMana:80,power:10,defense:9,speed:11},starterSpells:["void_bolt","entropy"],special:{name:"Oblivion",description:"Tear at the enemy with void magic, weakening and draining them.",manaCost:30}},
{id:"sigilbinder",name:"Sigilbinder",emoji:"🔮",role:"Hybrid",description:"Manipulates magical power itself.",base:{maxHp:100,maxMana:85,power:11,defense:10,speed:10},starterSpells:["sigil_bolt","sigil_focus"],special:{name:"Arcane Convergence",description:"Collapse raw Sigil energy into a balanced strike and ward.",manaCost:30}}
];
export const ARCANE_PVE_ENEMIES:ArcanePveEnemy[]=[
{id:"ember_wraith",name:"Ember Wraith",emoji:"🔥",rarity:"Common",description:"A restless flame spirit prowling the outer realm.",maxHp:85,maxMana:40,power:10,defense:6,speed:9,rewardXp:40,rewardSigils:5},
{id:"frostbound_sentinel",name:"Frostbound Sentinel",emoji:"❄️",rarity:"Uncommon",description:"An ancient guardian carved from enchanted ice.",maxHp:125,maxMana:50,power:12,defense:11,speed:6,rewardXp:65,rewardSigils:8},
{id:"void_stalker",name:"Void Stalker",emoji:"🌑",rarity:"Rare",description:"A creature that hunts where the light of the realm fades.",maxHp:150,maxMana:60,power:15,defense:10,speed:13,rewardXp:90,rewardSigils:12},
{id:"astral_archon",name:"Astral Archon",emoji:"🌌",rarity:"Epic",description:"A powerful sentinel of the deeper Arcane Realm.",maxHp:210,maxMana:80,power:19,defense:14,speed:11,rewardXp:140,rewardSigils:20},
{id:"runic_troll",name:"Runic Troll",emoji:"👹",rarity:"Common",description:"A hulking bridge troll covered in old wizarding runes.",maxHp:110,maxMana:20,power:13,defense:9,speed:5,rewardXp:45,rewardSigils:5},
{id:"hexed_goblin",name:"Hexed Goblin",emoji:"👺",rarity:"Common",description:"A sneaky goblin who learned just enough spellcraft to be dangerous.",maxHp:75,maxMana:45,power:11,defense:5,speed:15,rewardXp:45,rewardSigils:6},
{id:"enchanted_golem",name:"Enchanted Golem",emoji:"🗿",rarity:"Uncommon",description:"A stone guardian animated by a forgotten spell.",maxHp:145,maxMana:30,power:14,defense:15,speed:4,rewardXp:70,rewardSigils:8},
{id:"witchwood_wolf",name:"Witchwood Wolf",emoji:"🐺",rarity:"Uncommon",description:"A moon-touched beast that prowls the forests beyond the wizard roads.",maxHp:105,maxMana:35,power:14,defense:7,speed:17,rewardXp:65,rewardSigils:8},
{id:"cursed_knight",name:"Cursed Knight",emoji:"🛡️",rarity:"Rare",description:"A fallen guardian bound to an ancient sorcerer's oath.",maxHp:165,maxMana:40,power:17,defense:13,speed:8,rewardXp:95,rewardSigils:13},
{id:"bog_witch",name:"Bog Witch",emoji:"🧙",rarity:"Rare",description:"A swamp-dwelling spellcaster whose curses linger long after the duel.",maxHp:130,maxMana:90,power:17,defense:8,speed:10,rewardXp:100,rewardSigils:14},
{id:"tower_chimera",name:"Tower Chimera",emoji:"🐲",rarity:"Epic",description:"A magical beast stitched from the nightmares of an abandoned wizard tower.",maxHp:195,maxMana:70,power:20,defense:12,speed:12,rewardXp:135,rewardSigils:19},
{id:"fallen_apprentice",name:"Fallen Apprentice",emoji:"🧙‍♂️",rarity:"Epic",description:"A rogue apprentice wielding unstable magic stolen from the Grand Archive.",maxHp:180,maxMana:110,power:21,defense:10,speed:14,rewardXp:150,rewardSigils:21},
{id:"ancient_spellwyrm",name:"Ancient Spellwyrm",emoji:"🐉",rarity:"Legendary",description:"A dragon that fed for centuries on raw arcane energy.",maxHp:260,maxMana:120,power:24,defense:16,speed:13,rewardXp:220,rewardSigils:30}
];
export const ARCANE_ITEMS:ArcaneItem[]=[
{id:"ember_bolt",name:"Ember Bolt",emoji:"🔥",kind:"spell",rarity:"common",cost:0,description:"Reliable fire damage.",classId:"ember_mage",effect:{type:"damage",value:18},manaCost:8,minLevel:1},
{id:"ember_ward",name:"Ember Ward",emoji:"🛡️",kind:"spell",rarity:"common",cost:0,description:"Raise a protective ward.",classId:"ember_mage",effect:{type:"shield",value:14},manaCost:8,minLevel:1},
{id:"frost_shard",name:"Frost Shard",emoji:"❄️",kind:"spell",rarity:"common",cost:0,description:"Cold damage.",classId:"frostweaver",effect:{type:"damage",value:16},manaCost:8,minLevel:1},
{id:"frost_veil",name:"Frost Veil",emoji:"🧊",kind:"spell",rarity:"common",cost:0,description:"Reduce incoming damage.",classId:"frostweaver",effect:{type:"guard",value:16},manaCost:8,minLevel:1},
{id:"verdant_bloom",name:"Verdant Bloom",emoji:"🌿",kind:"spell",rarity:"common",cost:0,description:"Restore health.",classId:"verdant_warden",effect:{type:"heal",value:22},manaCost:8,minLevel:1},
{id:"thorn_guard",name:"Thorn Guard",emoji:"🌱",kind:"spell",rarity:"common",cost:0,description:"Raise a shield.",classId:"verdant_warden",effect:{type:"shield",value:18},manaCost:8,minLevel:1},
{id:"storm_bolt",name:"Storm Bolt",emoji:"⚡",kind:"spell",rarity:"common",cost:0,description:"Fast lightning damage.",classId:"storm_herald",effect:{type:"damage",value:17},manaCost:8,minLevel:1},
{id:"thunderstep",name:"Thunderstep",emoji:"⚡",kind:"spell",rarity:"common",cost:0,description:"Strike with lightning.",classId:"storm_herald",effect:{type:"damage",value:14},manaCost:8,minLevel:1},
{id:"void_bolt",name:"Void Bolt",emoji:"🌑",kind:"spell",rarity:"common",cost:0,description:"Precise void damage.",classId:"voidcaller",effect:{type:"damage",value:16},manaCost:8,minLevel:1},
{id:"entropy",name:"Entropy",emoji:"🕳️",kind:"spell",rarity:"common",cost:0,description:"Weaken the enemy.",classId:"voidcaller",effect:{type:"weaken",value:10},manaCost:8,minLevel:1},
{id:"sigil_bolt",name:"Sigil Bolt",emoji:"🔮",kind:"spell",rarity:"common",cost:0,description:"Balanced arcane damage.",classId:"sigilbinder",effect:{type:"damage",value:16},manaCost:8,minLevel:1},
{id:"sigil_focus",name:"Sigil Focus",emoji:"🔮",kind:"spell",rarity:"common",cost:0,description:"Recover Mana.",classId:"sigilbinder",effect:{type:"mana",value:20},manaCost:8,minLevel:1},
{id:"ember_flare",name:"Ember Flare",emoji:"🔥",kind:"spell",rarity:"uncommon",cost:40,description:"The Ember Mage's first true upgrade: a heavier flame burst.",classId:"ember_mage",effect:{type:"damage",value:26},manaCost:13,minLevel:3},
{id:"flame_burst",name:"Flame Burst",emoji:"💥",kind:"spell",rarity:"uncommon",cost:60,description:"A concentrated wave of fire for decisive damage.",classId:"ember_mage",effect:{type:"damage",value:32},manaCost:14,minLevel:5},
{id:"cinder_lance",name:"Cinder Lance",emoji:"🔥",kind:"spell",rarity:"rare",cost:90,description:"A piercing lance of flame that hits through defensive play.",classId:"ember_mage",effect:{type:"damage",value:40},manaCost:18,minLevel:8},
{id:"infernal_core",name:"Infernal Core",emoji:"🌋",kind:"spell",rarity:"legendary",cost:125,description:"Master the living core of the Ember path.",classId:"ember_mage",effect:{type:"damage",value:52},manaCost:24,minLevel:12},
{id:"frost_lance",name:"Frost Lance",emoji:"❄️",kind:"spell",rarity:"uncommon",cost:40,description:"A focused strike that begins the Frostweaver's control path.",classId:"frostweaver",effect:{type:"weaken",value:12},manaCost:13,minLevel:3},
{id:"glacial_bind",name:"Glacial Bind",emoji:"⛓️",kind:"spell",rarity:"uncommon",cost:60,description:"Cold magic that damages while disrupting the enemy.",classId:"frostweaver",effect:{type:"damage",value:25},manaCost:14,minLevel:5},
{id:"winter_grasp",name:"Winter's Grasp",emoji:"🧊",kind:"spell",rarity:"rare",cost:90,description:"A punishing frost spell that leaves the enemy weakened.",classId:"frostweaver",effect:{type:"weaken",value:15},manaCost:18,minLevel:8},
{id:"absolute_frost",name:"Absolute Frost",emoji:"🌨️",kind:"spell",rarity:"legendary",cost:125,description:"Freeze the battlefield beneath overwhelming ancient cold.",classId:"frostweaver",effect:{type:"damage",value:46},manaCost:24,minLevel:12},
{id:"verdant_surge",name:"Verdant Surge",emoji:"🌿",kind:"spell",rarity:"uncommon",cost:40,description:"A burst of living magic that restores health and raises a ward.",classId:"verdant_warden",effect:{type:"heal",value:28},manaCost:13,minLevel:3},
{id:"lifeweave",name:"Lifeweave",emoji:"✨",kind:"spell",rarity:"uncommon",cost:60,description:"Strong restoration for a Warden who refuses to fall.",classId:"verdant_warden",effect:{type:"heal",value:36},manaCost:14,minLevel:5},
{id:"ancient_bark",name:"Ancient Bark",emoji:"🌳",kind:"spell",rarity:"rare",cost:90,description:"Wrap yourself in an ancient living ward.",classId:"verdant_warden",effect:{type:"shield",value:30},manaCost:18,minLevel:8},
{id:"worldroot",name:"Worldroot",emoji:"🌲",kind:"spell",rarity:"legendary",cost:125,description:"Call on the oldest roots of the Realm to restore and protect you.",classId:"verdant_warden",effect:{type:"heal",value:52},manaCost:24,minLevel:12},
{id:"storm_arc",name:"Storm Arc",emoji:"⚡",kind:"spell",rarity:"uncommon",cost:40,description:"Lightning leaps through the target with brutal speed.",classId:"storm_herald",effect:{type:"damage",value:27},manaCost:13,minLevel:3},
{id:"chain_lightning",name:"Chain Lightning",emoji:"🌩️",kind:"spell",rarity:"uncommon",cost:60,description:"A stronger burst that rewards the Storm Herald's tempo.",classId:"storm_herald",effect:{type:"damage",value:30},manaCost:14,minLevel:5},
{id:"tempest_lance",name:"Tempest Lance",emoji:"🌪️",kind:"spell",rarity:"rare",cost:90,description:"A compressed thunderbolt built for decisive turns.",classId:"storm_herald",effect:{type:"damage",value:40},manaCost:18,minLevel:8},
{id:"storm_sovereign",name:"Storm Sovereign",emoji:"⛈️",kind:"spell",rarity:"legendary",cost:125,description:"Become the eye of the storm and unleash catastrophic lightning.",classId:"storm_herald",effect:{type:"damage",value:54},manaCost:24,minLevel:12},
{id:"void_mark",name:"Void Mark",emoji:"🌑",kind:"spell",rarity:"uncommon",cost:40,description:"Mark the enemy with unstable void energy.",classId:"voidcaller",effect:{type:"weaken",value:14},manaCost:13,minLevel:3},
{id:"void_drain",name:"Void Drain",emoji:"🌑",kind:"spell",rarity:"uncommon",cost:60,description:"Damage the enemy and recover part of the harm dealt.",classId:"voidcaller",effect:{type:"drain",value:22},manaCost:14,minLevel:5},
{id:"soul_rift",name:"Soul Rift",emoji:"🩸",kind:"spell",rarity:"rare",cost:90,description:"Rip through the enemy while feeding the caster's strength.",classId:"voidcaller",effect:{type:"drain",value:34},manaCost:18,minLevel:8},
{id:"null_field",name:"Null Field",emoji:"🕳️",kind:"spell",rarity:"legendary",cost:125,description:"Collapse the enemy's magical certainty beneath the void.",classId:"voidcaller",effect:{type:"weaken",value:18},manaCost:24,minLevel:12},
{id:"sigil_echo",name:"Sigil Echo",emoji:"🔮",kind:"spell",rarity:"uncommon",cost:40,description:"Restore magical reserves with a measured arcane pulse.",classId:"sigilbinder",effect:{type:"mana",value:18},manaCost:13,minLevel:3},
{id:"arcane_surge",name:"Arcane Surge",emoji:"✨",kind:"spell",rarity:"uncommon",cost:60,description:"Reliable arcane force for the adaptable Sigilbinder.",classId:"sigilbinder",effect:{type:"damage",value:28},manaCost:14,minLevel:5},
{id:"sigil_fracture",name:"Sigil Fracture",emoji:"💠",kind:"spell",rarity:"rare",cost:90,description:"Shatter the enemy with unstable sigil energy.",classId:"sigilbinder",effect:{type:"damage",value:38},manaCost:18,minLevel:8},
{id:"grand_convergence",name:"Grand Convergence",emoji:"🌌",kind:"spell",rarity:"legendary",cost:125,description:"Collapse raw Arcane power into a devastating final convergence.",classId:"sigilbinder",effect:{type:"damage",value:50},manaCost:24,minLevel:12},
{id:"apprentice_robes",name:"Apprentice Robes",emoji:"🧥",kind:"armor",rarity:"common",cost:0,description:"Starter robes for every new Wizard.",stats:{defense:2},minLevel:1},
{id:"bulwark_hide",name:"Bulwark Hide",emoji:"🛡️",kind:"armor",rarity:"uncommon",cost:45,description:"A sturdy first step toward a high-survivability build.",stats:{defense:8,maxHp:8,speed:-1},minLevel:3},
{id:"bulwark_plate",name:"Bulwark Plate",emoji:"🛡️",kind:"armor",rarity:"rare",cost:80,description:"Heavy warded plate built to outlast long Trials.",stats:{defense:12,maxHp:15,speed:-2},minLevel:6},
{id:"bulwark_aegis",name:"Bulwark Aegis",emoji:"🏰",kind:"armor",rarity:"epic",cost:125,description:"A fortress in armor form: immense defense at a real speed cost.",stats:{defense:17,maxHp:24,speed:-3},minLevel:10},
{id:"duelist_mantle",name:"Duelist Mantle",emoji:"⚔️",kind:"armor",rarity:"uncommon",cost:45,description:"Light armor for Wizards who want pressure without becoming fragile.",stats:{power:3,speed:3,defense:-2},minLevel:3},
{id:"duelist_raiment",name:"Duelist Raiment",emoji:"⚔️",kind:"armor",rarity:"rare",cost:80,description:"Refined combat robes that trade protection for tempo and force.",stats:{power:6,speed:4,defense:-3},minLevel:6},
{id:"duelist_regalia",name:"Duelist Regalia",emoji:"👑",kind:"armor",rarity:"epic",cost:125,description:"Prestige battlewear for aggressive Wizards who live by initiative.",stats:{power:9,speed:5,defense:-4},minLevel:10},
{id:"mystic_vestment",name:"Mystic Vestment",emoji:"🔮",kind:"armor",rarity:"uncommon",cost:45,description:"Arcane-threaded robes that expand magical reserves.",stats:{maxMana:12,power:1,defense:-1},minLevel:3},
{id:"mystic_raiment",name:"Mystic Raiment",emoji:"🔮",kind:"armor",rarity:"rare",cost:80,description:"Deep-channeling robes for spell-heavy builds.",stats:{maxMana:20,power:3,defense:-2},minLevel:6},
{id:"mystic_crown",name:"Mystic Crown",emoji:"🌌",kind:"armor",rarity:"epic",cost:125,description:"A masterwork channeling set that turns Mana into sustained options.",stats:{maxMana:30,power:5,defense:-3},minLevel:10},
{id:"warden_mail",name:"Warden Mail",emoji:"🌿",kind:"armor",rarity:"uncommon",cost:45,description:"Balanced protection with enough weight to hold a line.",stats:{defense:5,maxHp:6},minLevel:3},
{id:"warden_raiment",name:"Warden Raiment",emoji:"🌿",kind:"armor",rarity:"rare",cost:80,description:"A dependable all-rounder for Wizards who value consistency.",stats:{defense:8,maxHp:12,power:1},minLevel:6},
{id:"warden_heartwood",name:"Warden Heartwood",emoji:"🌳",kind:"armor",rarity:"epic",cost:125,description:"A masterwork balance of defense, vitality and magical force.",stats:{defense:11,maxHp:18,power:2},minLevel:10},
{id:"apprentice_wand",name:"Apprentice Wand",emoji:"🪄",kind:"focus",rarity:"common",cost:0,description:"Starter magical focus.",stats:{power:2},minLevel:1},
{id:"spellweaver_focus",name:"Spellweaver Focus",emoji:"📜",kind:"focus",rarity:"uncommon",cost:40,description:"Expands Mana and slightly strengthens every magical decision.",stats:{maxMana:10,power:1},minLevel:3},
{id:"spellweaver_orb",name:"Spellweaver Orb",emoji:"🔮",kind:"focus",rarity:"rare",cost:75,description:"A deep reservoir for Wizards who cast often.",stats:{maxMana:18,power:2},minLevel:7},
{id:"battlemage_focus",name:"Battlemage Focus",emoji:"⚔️",kind:"focus",rarity:"uncommon",cost:40,description:"A combat focus that makes direct magical attacks hit harder.",stats:{power:4,defense:-1},minLevel:3},
{id:"battlemage_core",name:"Battlemage Core",emoji:"💠",kind:"focus",rarity:"rare",cost:75,description:"A volatile core for aggressive spell-and-strike builds.",stats:{power:7,defense:-2},minLevel:7},
{id:"tempest_focus",name:"Tempest Focus",emoji:"⚡",kind:"focus",rarity:"uncommon",cost:40,description:"A quicksilver focus for Wizards who value speed.",stats:{speed:4,power:1},minLevel:3},
{id:"tempest_prism",name:"Tempest Prism",emoji:"⚡",kind:"focus",rarity:"rare",cost:75,description:"A refined lightning prism that pushes tempo even further.",stats:{speed:6,power:2},minLevel:7},
{id:"aegis_focus",name:"Aegis Focus",emoji:"🛡️",kind:"focus",rarity:"uncommon",cost:40,description:"A defensive focus that turns magical reserve into staying power.",stats:{defense:4,maxMana:5},minLevel:3},
{id:"aegis_relicum",name:"Aegis Relicum",emoji:"🏛️",kind:"focus",rarity:"rare",cost:75,description:"A master defensive focus for Wizards who prefer control and endurance.",stats:{defense:7,maxMana:9},minLevel:7},
{id:"emberglass",name:"Emberglass",emoji:"🔶",kind:"relic",rarity:"uncommon",cost:55,description:"A one-use emergency ward that can turn a dangerous turn around.",effect:{type:"shield",value:20}},
{id:"feather_astraeos",name:"Feather of Astraeos",emoji:"🪶",kind:"relic",rarity:"rare",cost:85,description:"A one-use evasive charm that can protect you through a critical exchange.",effect:{type:"evasion",value:15}},
{id:"lunar_eye",name:"Lunar Eye",emoji:"🌙",kind:"relic",rarity:"epic",cost:120,description:"A one-use initiative relic that lets you seize the tempo immediately.",effect:{type:"initiative",value:4}},
{id:"verdant_seed",name:"Verdant Seed",emoji:"🌱",kind:"relic",rarity:"rare",cost:75,description:"Crack the seed once to call a burst of restorative life.",effect:{type:"heal",value:25}},
{id:"mana_prism",name:"Mana Prism",emoji:"💎",kind:"relic",rarity:"rare",cost:75,description:"A one-use reserve of concentrated arcane energy.",effect:{type:"mana",value:30}},
{id:"astral_bell",name:"Astral Bell",emoji:"🔔",kind:"relic",rarity:"epic",cost:110,description:"A rare emergency focus that restores both health and Mana.",effect:{type:"astral_tonic",value:1}},
{id:"ember_aura",name:"Ember Aura",emoji:"🔥",kind:"cosmetic",rarity:"uncommon",cost:35,description:"A cosmetic ember aura for your Wizard's profile."},
{id:"frost_halo",name:"Frost Halo",emoji:"❄️",kind:"cosmetic",rarity:"uncommon",cost:35,description:"A cosmetic ring of winter magic."},
{id:"verdant_vines",name:"Verdant Vines",emoji:"🌿",kind:"cosmetic",rarity:"uncommon",cost:40,description:"A cosmetic wreath of living arcane vines."},
{id:"storm_crown",name:"Storm Crown",emoji:"⚡",kind:"cosmetic",rarity:"rare",cost:60,description:"A cosmetic crown crackling with harmless stormlight."},
{id:"astral_aura",name:"Astral Aura",emoji:"🌌",kind:"cosmetic",rarity:"rare",cost:70,description:"A cosmetic starlit aura for the Realm's night scholars."},
{id:"void_mask",name:"Void Mask",emoji:"🎭",kind:"cosmetic",rarity:"epic",cost:90,description:"A mysterious cosmetic mask touched by the outer dark."},
{id:"sigil_circlet",name:"Sigil Circlet",emoji:"💠",kind:"cosmetic",rarity:"epic",cost:100,description:"A cosmetic circlet etched with luminous Realm sigils."},
{id:"realm_master_signet",name:"Realm Master Signet",emoji:"🜏",kind:"cosmetic",rarity:"legendary",cost:150,description:"A prestigious cosmetic signet inspired by the keepers of the Realm."},
{id:"minor_healing_draught",name:"Minor Healing Draught",emoji:"🧪",kind:"consumable",rarity:"common",cost:15,description:"Restore 30 HP. Can be purchased and carried in multiple copies.",effect:{type:"heal",value:30}},
{id:"mana_elixir",name:"Mana Elixir",emoji:"🔵",kind:"consumable",rarity:"common",cost:18,description:"Restore 25 Mana. Can be purchased and carried in multiple copies.",effect:{type:"mana",value:25}},
{id:"ward_tonic",name:"Ward Tonic",emoji:"🛡️",kind:"consumable",rarity:"uncommon",cost:22,description:"Gain 22 Ward. Can be purchased and carried in multiple copies.",effect:{type:"shield",value:22}},
{id:"greater_healing_elixir",name:"Greater Healing Elixir",emoji:"❤️",kind:"consumable",rarity:"rare",cost:40,description:"Restore 55 HP. Can be purchased and carried in multiple copies.",effect:{type:"heal",value:55}},
{id:"greater_mana_elixir",name:"Greater Mana Elixir",emoji:"💙",kind:"consumable",rarity:"rare",cost:45,description:"Restore 50 Mana. Can be purchased and carried in multiple copies.",effect:{type:"mana",value:50}},
{id:"astral_tonic",name:"Astral Tonic",emoji:"🌌",kind:"consumable",rarity:"epic",cost:65,description:"Restore 35 HP and 30 Mana. A prized emergency tonic.",effect:{type:"astral_tonic",value:1}}
];
export function getClass(id:string){return ARCANE_CLASSES.find(x=>x.id===id);}
export function getPveEnemy(id:string){return ARCANE_PVE_ENEMIES.find(x=>x.id===id);}
export function getRandomPveEnemy(){return ARCANE_PVE_ENEMIES[Math.floor(Math.random()*ARCANE_PVE_ENEMIES.length)];}
export function getItem(id:string){return ARCANE_ITEMS.find(x=>x.id===id);}
export function getItems(kind?:ArcaneItemKind){return kind?ARCANE_ITEMS.filter(x=>x.kind===kind):ARCANE_ITEMS;}