import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, MessageFlags, StringSelectMenuBuilder, UserSelectMenuBuilder, type ButtonInteraction, type Interaction, type StringSelectMenuInteraction, type UserSelectMenuInteraction } from "discord.js";
import { prisma } from "../database/prisma.js";
import { arcaneStore } from "./store.js";
import { battleStore } from "./battleStore.js";
import { ARCANE_CLASSES, getClass, getItems, getPveEnemy } from "./catalog.js";

export const ARCANE_COUNCIL_PREFIX = "woa:council:arcane";
const button=(label:string,id:string,style:ButtonStyle=ButtonStyle.Primary)=>new ButtonBuilder().setLabel(label).setCustomId(id).setStyle(style);
const back=()=>new ActionRowBuilder<ButtonBuilder>().addComponents(button("◀ Council","woa:council:home",ButtonStyle.Secondary));

export function buildArcaneCouncilPanel(){
  return {embeds:[new EmbedBuilder().setColor(0x4B0082).setTitle("🔮 ARCANE COUNCIL").setDescription("The Council chamber for the Arcane Realm. Monitor Wizards, Trials, progression and the game's original content without leaving the Council panel.").addFields(
    {name:"🧙 Wizards",value:"Inspect players and grant progression.",inline:true},{name:"⚔️ Trials",value:"Monitor and close active battles.",inline:true},{name:"📚 Codex",value:"Review classes, spells, relics and gear.",inline:true})],
    components:[new ActionRowBuilder<ButtonBuilder>().addComponents(button("🧙 Manage Wizards",ARCANE_COUNCIL_PREFIX+":players"),button("⚔️ Active Trials",ARCANE_COUNCIL_PREFIX+":battles"),button("📚 Codex",ARCANE_COUNCIL_PREFIX+":codex")),new ActionRowBuilder<ButtonBuilder>().addComponents(button("📊 Realm Stats",ARCANE_COUNCIL_PREFIX+":stats"),button("◀ Council","woa:council:home",ButtonStyle.Secondary))]};
}

async function stats(i:ButtonInteraction){const guildId=i.guildId!;const [wizards,activeBattles]=await Promise.all([prisma.arcaneCharacter.count({where:{guildId}}),prisma.arcaneBattle.count({where:{guildId,status:"active"}})]);const top=await arcaneStore.top(guildId);await i.update({embeds:[new EmbedBuilder().setColor(0xD4AF37).setTitle("📊 ARCANE REALM STATISTICS").setDescription("A live view of the mini-game's current state.").addFields({name:"🧙 Wizards",value:String(wizards),inline:true},{name:"⚔️ Active Trials",value:String(activeBattles),inline:true},{name:"📚 Classes",value:String(ARCANE_CLASSES.length),inline:true},{name:"✨ Catalog Items",value:String(getItems().length),inline:true},{name:"🏆 Leading Wizard",value:top[0]?top[0].name+" • Lv "+top[0].level+" • "+top[0].xp+" XP":"No Wizards yet",inline:false})],components:[back()]});}

async function players(i:ButtonInteraction){const menu=new UserSelectMenuBuilder().setCustomId(ARCANE_COUNCIL_PREFIX+":player").setPlaceholder("Select a Wizard to inspect").setMinValues(1).setMaxValues(1);await i.update({embeds:[new EmbedBuilder().setColor(0x4B0082).setTitle("🧙 MANAGE WIZARDS").setDescription("Select a Discord member. Council controls here affect only their Arcane Realm character.")],components:[new ActionRowBuilder<UserSelectMenuBuilder>().addComponents(menu),back()]});}

async function player(i:UserSelectMenuInteraction){const userId=i.values[0],c=await arcaneStore.get(i.guildId!,userId);if(!c){await i.reply({content:"That player has not created an Arcane Wizard yet.",flags:MessageFlags.Ephemeral});return;}const cl=getClass(c.classId)!;await i.update({embeds:[new EmbedBuilder().setColor(0x6A0DAD).setTitle("🧙 WIZARD OVERSIGHT").setDescription("**"+c.name+"** • "+cl.emoji+" "+cl.name+"\n<@"+c.userId+">\nLevel **"+c.level+"** • XP **"+c.xp+"/"+c.level*100+"**\n❤️ "+c.hp+" HP • 🔮 "+c.mana+" Mana").addFields({name:"🛡️ Armor",value:c.armorId,inline:true},{name:"🪄 Focus",value:c.focusId,inline:true},{name:"🔶 Relics",value:String(c.relicIds.length),inline:true})],components:[new ActionRowBuilder<ButtonBuilder>().addComponents(button("✨ +100 XP",ARCANE_COUNCIL_PREFIX+":xp:"+userId+":100"),button("✨ +500 XP",ARCANE_COUNCIL_PREFIX+":xp:"+userId+":500")),new ActionRowBuilder<ButtonBuilder>().addComponents(button("🜂 Reset Wizard",ARCANE_COUNCIL_PREFIX+":reset:"+userId,ButtonStyle.Danger),button("◀ Players",ARCANE_COUNCIL_PREFIX+":players",ButtonStyle.Secondary))]});}

async function awardXp(i:ButtonInteraction,userId:string,amount:number){const c=await arcaneStore.get(i.guildId!,userId);if(!c){await i.reply({content:"Wizard not found.",flags:MessageFlags.Ephemeral});return;}await arcaneStore.addXp(c,amount);await i.reply({content:"✨ Granted **"+amount+" XP** to **"+c.name+"**.",flags:MessageFlags.Ephemeral});}

async function reset(i:ButtonInteraction,userId:string){await prisma.arcaneBattle.deleteMany({where:{guildId:i.guildId!,OR:[{challengerId:userId},{opponentId:userId}]}});const c=await arcaneStore.get(i.guildId!,userId);if(c)await prisma.arcaneCharacter.delete({where:{id:c.id}});await i.update({embeds:[new EmbedBuilder().setColor(0xB22222).setTitle("🜂 WIZARD RESET").setDescription("The Arcane character for <@"+userId+"> has been reset. Their Discord Sigils were **not** changed.")],components:[new ActionRowBuilder<ButtonBuilder>().addComponents(button("◀ Manage Wizards",ARCANE_COUNCIL_PREFIX+":players",ButtonStyle.Secondary),button("◀ Council","woa:council:home",ButtonStyle.Secondary))]});}

async function battles(i:ButtonInteraction){const rows=await prisma.arcaneBattle.findMany({where:{guildId:i.guildId!,status:"active"},orderBy:{createdAt:"asc"},take:25});if(!rows.length){await i.update({embeds:[new EmbedBuilder().setColor(0x4B0082).setTitle("⚔️ ACTIVE TRIALS").setDescription("No Arcane Trials are active.")],components:[back()]});return;}const menu=new StringSelectMenuBuilder().setCustomId(ARCANE_COUNCIL_PREFIX+":battle").setPlaceholder("Select a Trial to inspect");menu.addOptions(rows.map((b:any)=>({label:(b.challengerId+" vs "+b.opponentId).slice(0,100),value:b.id,description:("Round "+b.round+" • Turn: "+b.turnUserId).slice(0,100)})));await i.update({embeds:[new EmbedBuilder().setColor(0x6A0DAD).setTitle("⚔️ ACTIVE TRIALS").setDescription(rows.length+" active Trial"+(rows.length===1?"":"s")+". Select one for Council oversight.")],components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(menu),back()]});}

async function battle(i:StringSelectMenuInteraction){const b:any=await battleStore.get(i.values[0]);if(!b||b.guildId!==i.guildId||b.status!=="active"){await i.reply({content:"That Trial is no longer active.",flags:MessageFlags.Ephemeral});return;}const a=await arcaneStore.get(i.guildId!,b.challengerId),o=await arcaneStore.get(i.guildId!,b.opponentId),enemy=b.opponentId.startsWith("npc:")?getPveEnemy(b.opponentId.slice(4)):null,s:any=b.state;const opponentName=enemy?enemy.emoji+" "+enemy.name:(o?.name||b.opponentId);await i.update({embeds:[new EmbedBuilder().setColor(enemy?0x8B4513:0x8B0000).setTitle(enemy?"🏹 PvE TRIAL OVERSIGHT":"⚔️ TRIAL OVERSIGHT").setDescription("**"+(a?.name||b.challengerId)+"** ❤️ "+(s[b.challengerId]?.hp??0)+" HP\n**VS**\n**"+opponentName+"** ❤️ "+(s[b.opponentId]?.hp??0)+" HP\n\nRound **"+b.round+"** • Turn <@"+b.turnUserId+">")],components:[new ActionRowBuilder<ButtonBuilder>().addComponents(button("🛑 Close Trial",ARCANE_COUNCIL_PREFIX+":close:"+b.id,ButtonStyle.Danger)),back()]});}

async function closeBattle(i:ButtonInteraction,id:string){const b:any=await battleStore.get(id);if(!b||b.guildId!==i.guildId||b.status!=="active"){await i.reply({content:"That Trial is already closed.",flags:MessageFlags.Ephemeral});return;}await prisma.arcaneBattle.update({where:{id},data:{status:"finished"}});await i.update({embeds:[new EmbedBuilder().setColor(0xB22222).setTitle("🛑 TRIAL CLOSED").setDescription("The Council has ended the active Trial. No winner reward was issued.")],components:[back()]});}

async function codex(i:ButtonInteraction){const spells=getItems("spell"),gear=getItems().filter(x=>x.kind!=="spell");const text="**Classes**\n"+ARCANE_CLASSES.map(x=>x.emoji+" **"+x.name+"** — "+x.role+"\n"+x.description).join("\n\n")+"\n\n**Gear**\n"+gear.map(x=>x.emoji+" **"+x.name+"** — "+x.rarity+" • "+x.cost+" Sigils").join("\n")+"\n\n**Spells**\n"+spells.map(x=>x.emoji+" **"+x.name+"** — "+x.rarity+" • "+x.cost+" Sigils").join("\n");await i.update({embeds:[new EmbedBuilder().setColor(0x4B0082).setTitle("📚 ARCANE CODEX • COUNCIL VIEW").setDescription(text.slice(0,4000))],components:[back()]});}

export async function handleArcaneCouncilPanel(i:Interaction){if(!("customId" in i)||typeof i.customId!=="string")return false;if(!i.customId.startsWith(ARCANE_COUNCIL_PREFIX+":"))return false;const section=i.customId.slice((ARCANE_COUNCIL_PREFIX+":").length);if(i.isUserSelectMenu()&&section==="player"){await player(i);return true;}if(i.isStringSelectMenu()&&section==="battle"){await battle(i);return true;}if(!i.isButton())return true;if(section==="home"){await i.update(buildArcaneCouncilPanel());return true;}if(section==="players"){await players(i);return true;}if(section==="battles"){await battles(i);return true;}if(section==="codex"){await codex(i);return true;}if(section==="stats"){await stats(i);return true;}const p=section.split(":");if(p[0]==="xp"&&p.length===3){await awardXp(i,p[1],Number(p[2]));return true;}if(p[0]==="reset"&&p[1]){await reset(i,p[1]);return true;}if(p[0]==="close"&&p[1]){await closeBattle(i,p[1]);return true;}return true;}
