import { randomUUID } from "node:crypto";
import { prisma } from "../database/prisma.js";
import { sigilStore } from "../sigilStore.js";
import { getClass,getItem,type ArcaneClassId } from "./catalog.js";
export interface ArcaneCharacterRecord { id:string;guildId:string;userId:string;name:string;classId:ArcaneClassId;level:number;xp:number;hp:number;mana:number;baseStats:any;equippedSpellIds:string[];ownedItemIds:string[];armorId:string;focusId:string;relicIds:string[];cosmetics:string[]; }
const rec=(r:any):ArcaneCharacterRecord=>({...r,baseStats:r.baseStats||{},equippedSpellIds:r.equippedSpellIds||[],ownedItemIds:(r.ownedItemIds||[]).filter((id:string)=>!!getItem(id)),relicIds:(r.relicIds||[]).filter((id:string)=>!!getItem(id)),cosmetics:(r.cosmetics||[]).filter((id:string)=>!!getItem(id))});
class ArcaneStore {
async get(guildId:string,userId:string){const r=await prisma.arcaneCharacter.findUnique({where:{guildId_userId:{guildId,userId}}});return r?rec(r):undefined;}
async create(guildId:string,userId:string,name:string,classId:ArcaneClassId){const cls=getClass(classId);if(!cls)throw new Error("Unknown class.");const old=await this.get(guildId,userId);if(old) return old;return rec(await prisma.arcaneCharacter.create({data:{id:randomUUID(),guildId,userId,name:name.trim().slice(0,32),classId,level:1,xp:0,hp:cls.base.maxHp,mana:cls.base.maxMana,baseStats:cls.base as any,equippedSpellIds:cls.starterSpells,ownedItemIds:["apprentice_robes","apprentice_wand",...cls.starterSpells],armorId:"apprentice_robes",focusId:"apprentice_wand",relicIds:[],cosmetics:[]}}));}
async save(c:ArcaneCharacterRecord){return rec(await prisma.arcaneCharacter.update({where:{id:c.id},data:{name:c.name,level:c.level,xp:c.xp,hp:c.hp,mana:c.mana,baseStats:c.baseStats as any,equippedSpellIds:c.equippedSpellIds,ownedItemIds:c.ownedItemIds,armorId:c.armorId,focusId:c.focusId,relicIds:c.relicIds,cosmetics:c.cosmetics}}));}
async addXp(c:ArcaneCharacterRecord,n:number){c.xp+=n;while(c.xp>=c.level*100){c.xp-=c.level*100;c.level++;}return this.save(c);}
async buy(guildId:string,userId:string,itemId:string){const c=await this.get(guildId,userId),item=getItem(itemId);if(!c||!item)throw new Error("Offering not found.");const permanent=item.kind==="spell"||item.kind==="armor"||item.kind==="focus"||item.kind==="cosmetic";if(item.kind==="spell"&&item.classId!==c.classId)throw new Error("That spell belongs to another Wizard class.");if(item.minLevel&&c.level<item.minLevel)throw new Error("You must reach **Level "+item.minLevel+"** to learn **"+item.name+"**.");if(c.ownedItemIds.includes(itemId))throw new Error("You already possess that.");if(permanent&&(c.ownedItemIds.includes(itemId)||c.cosmetics.includes(itemId)))throw new Error("You already possess that.");if(await sigilStore.getBalance(guildId,userId)<item.cost)throw new Error("Not enough Sigils.");await sigilStore.addTransaction(guildId,userId,-item.cost,"Arcane Trials purchase: "+item.name,{type:"redeem"});if(item.kind==="cosmetic")c.cosmetics.push(itemId);else c.ownedItemIds.push(itemId);return this.save(c);}
async equip(guildId:string,userId:string,itemId:string){const c=await this.get(guildId,userId),item=getItem(itemId);if(!c||!item||(!c.ownedItemIds.includes(itemId)&&!c.cosmetics.includes(itemId)))throw new Error("You do not own that offering.");if(item.kind==="spell"){if(!c.equippedSpellIds.includes(itemId)){if(c.equippedSpellIds.length>=4)throw new Error("Your spellbook has four slots.");c.equippedSpellIds.push(itemId);}}else if(item.kind==="armor")c.armorId=itemId;else if(item.kind==="focus")c.focusId=itemId;else if(item.kind==="relic"){if(!c.relicIds.includes(itemId)){if(c.relicIds.length>=2)throw new Error("You may carry two relics.");c.relicIds.push(itemId);}}return this.save(c);}
async list(guildId:string){return (await prisma.arcaneCharacter.findMany({where:{guildId},orderBy:[{name:"asc"}]})).map(rec);}
async top(guildId:string){return (await prisma.arcaneCharacter.findMany({where:{guildId},orderBy:[{level:"desc"},{xp:"desc"}],take:10})).map(rec);}
}
export const arcaneStore=new ArcaneStore();